config/routes.rb
Rails.application.routes.draw do

devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
  post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

  namespace :admin do
    resources :spots do
      resources :reviews
    end
    resources :customers do #, only: [:index, :show, :create, :edit, :update]
        resources :reviews
    end
    resources :genres, only: [:index, :create, :edit, :update]
     get "search" => "spots#search"
  end


scope module: :public do

    root 'homes#top'
    resources :spots do
    resources :reviews
  end
    # get "search" => "spots#search"
    resources :customers do #, only: [:index, :show, :create, :edit, :update]
    resources :reviews, only: [:destroy]
  end

  resources :customers do
   member do
       get 'confirm_withdraw'
       patch 'withdraw'
     end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  def show
     @review = Review.find(params[:id])
  end

  def index
      @customer = Customer.find(params[:customer_id])
      @reviews = Review.where(customer_id: @customer.id).page(params[:page]).per(10).reverse_order
  end


  def destroy
      unless params[:customer_id].nil?
        @customer = Customer.find(params[:customer_id])
      else
        @spot = Spot.find(params[:spot_id])
      end
      @comment = Review.find(params[:id])
      @comment.destroy
      if @spot.nil?
        redirect_to admin_customer_reviews_path(@customer)
      else
        redirect_to admin_spot_path(@spot)
      end
  end


  private

    def review_params
      params.require(:review).permit(:comment, :all_rating, :rating1, :rating2, :rating3, :rating4).merge(
         customer_id: current_customer.id, spot_id: params[:spot_id]
    )
    end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/_form.html.erb
<%= form_with(url: admin_spot_reviews_path(spot_id: spot.id), local: false) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100 comment-textarea" %>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/admin/reviews/_index.html.erb
<table>
  <tbody>
      <% spot.reviews.each do |review| %>
      <tr>

        <td>
          <%= link_to admin_customer_path(review.user) do %>
            <%= image_tag review.customer.get_profile_image, size: "100x100" %><br>
            <%= review.customer.nickname %>
            <%= review.created_at.strftime('%Y/%m/%d') %><%= review.comment %>
          <% end %>
        </td>
        <td><%= review.comment %></td>
        <td>
            <%= link_to "削除", spot_review_path(spot, review), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger pull-right", remote: true %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/admin/reviews/_list.html.erb
<% reviews.each do |review| %>
  <div class="row">
    <div class="col-12 col-md-3">
      <%= review.customer.nickname %>
      <%= review.created_at.strftime('%Y/%m/%d') %><br>
    </div>
    <div class="col-12 col-md-9">
      <div id="review-<%= review.id %>">
      </div>
      <script>
        var elem = document.getElementById("review-<%= review.id %>");
        var opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'review[all_rating]',
          half: true,
          readOnly: true,
          score: <%= review.all_rating %>
          };
          raty(elem,opt);
      </script>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-12 col-md-3">
      <%= link_to admin_customer_path(review.customer) do %>
      <%= image_tag review.customer.get_profile_image(60,60), class: "rounded-circle" %></br>
      <% end %>
    </div>
    <div class="col-12 col-md-7">
      <div class="content-body">
        <% if review.comment.length > 15 %>
          <div id="truncated_<%= review.id %>">
            <p><%= review.comment.truncate(15)%></p>
            <a id="see-more_<%= review.id %>" class="link-primary link">&lt;もっと見る&gt;</a>
          </div>
          <div id="untruncated_<%= review.id %>" class="hide">
            <p><%= review.comment %></p>
          </div>
        <% else %>
          <p><%= review.comment %></p>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-md-2">
         <%= link_to "削除", admin_spot_review_path(spot, review), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger pull-right", remote: true %>
    </div>
  </div>
  <script>
    $(document).ready(function () {
      $('#see-more_<%= review.id %>').on('click', function(){
        $('#untruncated_<%= review.id %>').removeClass('hide')
        $('#truncated_<%= review.id %>').addClass("hide")
        $('#see-more_<%= review.id %>').addClass("hide")
      });
    });
  </script>
<% end %>
<%= paginate reviews, theme: 'twitter-bootstrap-4' %>

app/views/admin/reviews/index.html.erb
<div class="container wrapper flex">
 <div class="row">
		<h2><%= @customer.nickname %>さんのレビュー履歴一覧</h2>
		<table class="table">
			<thead>
				<tr>
					<th>レビュー日</th>
					<th>スポット</th>
					<th>評価</th>
					<th>レビュー詳細</th>
					<th>削除</th>
				</tr>
			</thead>
			<tbody>
				<% @reviews.each do |review| %>
					<tr>
						<td style="width: 10%"><%= review.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
						<td style="width: 20%"><%= link_to review.spot.name, admin_spot_path(review.spot) %></td>
					<td id="review-<%= review.id %>">
	          <script>
	            var elem = document.getElementById("review-<%= review.id %>");
	            var opt = {
	              starOn: "<%= asset_path('star-on.png') %>",
	              starOff: "<%= asset_path('star-off.png') %>",
	              starHalf: "<%= asset_path('star-half.png') %>",
	              scoreName: 'review[all_rating]',
	              half: true,
	              readOnly: true,
	              score: <%= review.all_rating %>
	              };
	              raty(elem,opt);
	          </script>
	        </td>
						<td style="width: 50%">
							<div class="content-body">
	            <% if review.comment.length > 25 %>
	              <div id="truncated_<%= review.id %>">
	                <p><%= review.comment.truncate(25)%></p>
	                <a id="see-more_<%= review.id %>" class="link-primary link">&lt;もっと見る&gt;</a>
	              </div>
	              <div id="untruncated_<%= review.id %>" class="hide">
	                <p><%= review.comment %></p>
	              </div>
	            <% else %>
	              <p><%= review.comment %></p>
	            <% end %>
	          </div>
						<td style="width: 10%">
	            	<%= link_to "削除", admin_customer_review_path(@customer, review), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-outline-danger", remote: true %>
	          </td>
					</tr>
					<script>
				    $(document).ready(function () {
				      $('#see-more_<%= review.id %>').on('click', function(){
				        $('#untruncated_<%= review.id %>').removeClass('hide')
				        $('#truncated_<%= review.id %>').addClass("hide")
				        $('#see-more_<%= review.id %>').addClass("hide")
				      });
				    });
				  </script>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<%= paginate @reviews, theme: 'twitter-bootstrap-4' %>