config/routes.rb
Rails.application.routes.draw do

devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
  post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

  namespace :admin do
    resources :spots do
      resources :reviews
    end
    resources :customers do #, only: [:index, :show, :create, :edit, :update]
        resources :reviews
    end
    resources :genres, only: [:index, :create, :edit, :update]
     get "search" => "spots#search"
  end


scope module: :public do

    root 'homes#top'
    resources :spots do
    resources :reviews
  end
    # get "search" => "spots#search"
    resources :customers do #, only: [:index, :show, :create, :edit, :update]
    resources :reviews, only: [:destroy]
  end

  resources :customers do
   member do
       get 'confirm_withdraw'
       patch 'withdraw'
     end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/models/spot.rb
class Spot < ApplicationRecord

  has_one_attached :spot_image
  has_many :reviews, dependent: :destroy
  belongs_to :genre
  def self.search(keyword)
    where(["name like? OR address like? OR introduction like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  belongs_to :prefecture
  
  scope :where_genre_active, -> { joins(:genre).where(genres: { is_active: true }) }
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  
  validates :name, presence: true
  validates :address, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :prefecture_id, presence: true

  def average_score
    self.reviews.sum(:all_rating) / self.reviews.length
  end

  def get_spot_image(width, height)
  unless spot_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    spot_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    spot_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < ApplicationController

    def new
      @spot = Spot.new
    end

   def index
    @genres = Genre.only_active
    @genre = Genre.find_by(id: params[:genre_id])
    spots = params[:keyword].present? ? Spot.search(params[:keyword]) : Spot.all
    spots = spots.where(genre_id: params[:genre_id]) if params[:genre_id].present?
    spots = spots.where(prefecture_id: params[:prefecture_id]) if params[:prefecture_id].present?
    if params[:latest]
      spots = spots.latest
    elsif params[:old]
      spots = spots.old
    end
    @spots = spots.page(params[:page]).per(6)
    @all_spots_count = spots.length
   end

  def create
    @spot = Spot.new(spot_params)
    @spot.save ? (redirect_to admin_spot_path(@spot)) : (render :new)
  end

  def show
    @spot = Spot.where_genre_active.find(params[:id])
    @review = Review.new
    @genres = Genre.only_active
    @reviews = Review.where(spot:@spot).page(params[:page]).per(3).reverse_order
  end

  def edit
    @spot = Spot.where_genre_active.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      flash[:success] = "投稿の更新に成功しました"
      redirect_to admin_spot_path(@spot)
    else
      render :edit
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to admin_spots_path
  end

  private

  def spot_params
    params.require(:spot).permit(:genre_id, :name, :introduction, :spot_image, :address, :prefecture_id)
  end

end

app/helpers/admin/spots_helper.rb
module Admin::SpotsHelper
end

app/views/admin/spots/_search_sidebar.html.erb
<%= form_with url: admin_spots_path, method: :get, local: true do |f| %>
  <strong>ジャンル</strong><br>
    <%= f.radio_button :genre_id, "", checked: params[:genre_id] == '' %>
    <%= f.label :genre_id, 'すべてのジャンル', value: '' %> <br>
    <% genres.each do |genre| %>
      <%= f.radio_button :genre_id, genre.id, checked: params[:genre_id] == genre.id.to_s %>
      <%= f.label :genre_id, genre.name, value: genre.id %><br>
    <% end %>

  <strong>都道府県</strong><br>
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, selected: params[:prefecture_id], include_blank: true) %><br>

  <strong>フリーワード</strong><br>
    <%= f.text_field :keyword ,value: params[:keyword] %><br>
    <%= f.submit "検索" %>
    <% end %>

  <div class="genre-create">
    <%= link_to "☆ジャンル追加", admin_genres_path %>
  </div>

  <div class="genre-create">
    <%= link_to "☆スポット追加", new_admin_spot_path %>
  </div>

app/views/admin/spots/_serach.html.erb
<div class="search-form">
  <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword ,value: params[:keyword] %>
    <%# if params[:genre_id].present? %>
      <%#= f.hidden_field :genre_id, value: params[:genre_id] %>
    <%# end %>
    <%= f.submit "検索" %>
  <% end %>
</div>

<!--<div class="spot-list">-->
<!--  <%# spots.each do |spot| %>-->
    <!--<%#= spot.name %> title削除-->
<!--  <%# end %>-->
<!--</div>-->

app/views/admin/spots/edit.html.erb
<div class="container">
	<h2 class="section-ttl"><%= @spot.name %>の編集</h2>
		<div class="row justify-content-center">
			<%= form_with model: @spot, url: admin_spot_path(@spot) do |f| %>
			<div class="col-md-12">
		 		<div class="image_field">
					<%= image_tag @spot.get_spot_image(400, 400), class: "admin_image" %>
				</div>
				<span class="btn btn-file btn-info"><%= f.file_field :spot_image,  accept:'image/*' %></span>
				<p>選択するとプレビューされます。<br>画像未選択のままだと「No image」になります。</p>
			</div>

			<table class="admin_spot_info spot_form">
				<thead>
					<tr>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= f.label :name, "スポット名" %></td>
						<td><%= f.text_field :name, class: 'form-control',size: "60x10" %></td>
					</tr>
					<tr>
						<td><%= f.label :introduction, "説明" %></td>
						<td><%= f.text_area :introduction, rows: 3, class: 'form-control',size: "60x10" %></td>
					</tr>
					<tr>
						<td><%= f.label :genre_id, "ジャンル" %></td>
						<td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
					</tr>
					<tr>
						<td><%= f.label :address, "住所" %></td>
						<td><%= f.text_field :address, class: 'form-control',size: "60x10" %></td>
					</tr>
					<tr>
						<td><%= f.label :prefecture_id, "都道府県" %></td>
						<td class="select_field"><%= f.collection_select :prefecture_id, Prefecture.all, :id, :name %></td>
					</tr>
				</tbody>
			</table>
			<div class="flex text-center">
				<%= f.submit '更新', class: "btn btn-secondary" %>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/spots/index.html.erb
<div class="container wrapper flex">
	<div class="row">
		<div class="col-md-3 border rounded">
	 		<%= render 'admin/spots/search_sidebar', genres: @genres %>
	  </div>
		<div class="content col-md-9">
			<% if @genre.present? %>
				<h2 class="section-ttl">[管理者]ジャンル：<%= @genre.name %> (全<%= @all_spots_count %>件)</h2>
			<% else %>
				<h2 class="section-ttl">[管理者]スポット (全<%= @all_spots_count %>件)</h2>
			<% end %>
			<% if @spots.first %>
				<div>
					<i class="fas fa-sort-amount-down"></i><%= link_to '新しい順', admin_spots_path(latest: "true") %>
			     	<i class="fas fa-sort-amount-up-alt"></i><%= link_to '古い順', admin_spots_path(old: "true") %>
			    </div>
				<div class="spots row">
					<% @spots.each do |spot| %>
						<% if spot.genre.is_active == true %>
							<div class="col-4 mb-5">
								<%= link_to admin_spot_path(spot) do %>
									<%= image_tag spot.get_spot_image(250,200), class: "img-thumbnail spot_image" %>
									<div><%= spot.name %></div>
								<% end %>
								<p class="my-0">ジャンル：<%= spot.genre.name %></p>
								<!--<div class="average-review-rating" data-score=<%= spot.reviews.average(:all_rating) %>></div>-->
		　					<span>総合評価：<%= spot.reviews.average(:all_rating).to_f.round(1) %></span>
		　				</div>
		　			<% end %>
					<% end %>
				</div>
				<%= paginate @spots, theme: 'twitter-bootstrap-4' %>
			<% else %>
				<h3>対応するスポットはありませんでした。</h3>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/spots/new.html.erb
<div class="container wrapper flex">
	<h2 class="section-ttl">スポット新規登録</h2>
  <div class="row">
		<%= form_with model: @spot, url: admin_spots_path do |f| %>
			<%= render "public/shared/error_messages", resource: @spot %>
			<div class="flex">
				<div class="image_field">
					<%= image_tag (@spot.spot_image.attached? ? @spot.image : 'no_image.jpg'), id: "img_prev", class: "admin_spot_image" %>
					<span class="btn btn-file btn-info"><%= f.file_field :spot_image,  accept:'image/*' %>画像選択</span>
					<p>選択するとプレビューされます。<br>画像未選択のままだと、「No Image」になります。</p>
				</div>
			</div>
			<table class="admin_item_info item_form">
				<thead>
					<tr>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= f.label :name, "スポット名" %></td>
						<td><%= f.text_field :name %></td>
					</tr>
					<tr>
						<td><%= f.label :introduction, "説明" %></td>
						<td><%= f.text_area :introduction, rows: 3, class: 'form-control',size: "60x10" %></td>
					</tr>
					<tr>
						<td><%= f.label :genre_id, "ジャンル" %></td>
						<td class="select_field"><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
					</tr>
					<tr>
						<td><%= f.label :address, "住所" %></td>
						<td><%= f.text_field :address %></td>
					</tr>
					<tr>
						<td><%= f.label :prefecture_id, "都道府県" %></td>
						<td class="select_field"><%= f.collection_select :prefecture_id, Prefecture.all, :id, :name %></td>
					</tr>
				</tbody>
			</table>
			<div class="flex align-center pl5">
				<%= f.submit '登録', class: "btn btn-primary" %>
			</div>
		<% end %>
  </div>
</div>

app/views/admin/spots/show.html.erb
<div class="container wrapper flex">
  <div class="row">
    <div class="col-md-3 border rounded">
      <%= render 'admin/spots/search_sidebar', genres: @genres %>
    </div>
    <div class="content col-md-9">
      <h2 class="section-ttl"><%= @spot.name %></h2>
    	<div class="flex">
    	  <%= image_tag @spot.get_spot_image(400, 400), class: "img-thumbnail spot_image_show" %>
    		  <div class="spot_info">
      		  <p>ジャンル: <%= link_to @spot.genre.name, admin_spots_path(genre_id: @spot.genre_id) %></p>
      			<p><%= @spot.address %></p><br>
      			<p><%= @spot.introduction %></p><br>
            <div class="text-right">
              <%= link_to "編集する",edit_admin_spot_path(@spot.id), class:"btn btn-outline-primary" %>
              <%= link_to "削除する",admin_spot_path(@spot.id), method: :delete, data: { confirm: '本当に消しますか？' }, class:"btn btn-outline-danger" %>
            </div>
            <h5>カスタマーレビュー</h5>
            <div class="average-review-rating" data-score=<%= @spot.reviews.average(:all_rating) %>></div>
            <p>総合評価：<%= @spot.reviews.average(:all_rating).to_f.round(1) %></p>
              <%= render "admin/reviews/list", spot: @spot, review: @review, reviews: @reviews %>
          </div>
        </div>
      </div>
    </div>
	</div>
</div>