config/routes.rb
Rails.application.routes.draw do

devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

devise_scope :customer do
  post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
end

  namespace :admin do
    resources :spots do
      resources :reviews
    end
    resources :customers do #, only: [:index, :show, :create, :edit, :update]
        resources :reviews
    end
    resources :genres, only: [:index, :create, :edit, :update]
     get "search" => "spots#search"
  end


scope module: :public do

    root 'homes#top'
    resources :spots do
    resources :reviews
  end
    # get "search" => "spots#search"
    resources :customers do #, only: [:index, :show, :create, :edit, :update]
    resources :reviews, only: [:destroy]
  end

  resources :customers do
   member do
       get 'confirm_withdraw'
       patch 'withdraw'
     end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/views/layouts/_flashmessage.html.erb
<% if notice %>
  <div class="alert-info" >
   <span><%= notice %></span>
  </div>
<% elsif flash[:success] %>
  <div class="alert-success">
   <span><%= flash[:success] %></span>
  </div>
<% else flash[:alert] %>
  <div class="alert-danger">
   <span><%= flash[:alert] %></span>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-black pt-5 pb-4 mt-5">
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    	  <p>hashimotohana_nanisuru.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm mb-3">
  <nav class="navbar navbar-expand-lg navbar-light mt-3 mb-3">
    <div class="container">
      <a class="navbar-brand p-3" href="/"><%= image_tag 'nanisuru_top.png' %></a>
      <ul class="navbar-nav nav-fill ml-auto">
        <% if customer_signed_in? %>
        
          <li class="customer-name mr-3">
          ようこそ、<%= current_customer.nickname %>さん！
          </li>
          <li class="nav-item mr-3"><i class="fas fa-user"></i><%= link_to "マイページ", customer_path(current_customer) %></li>
          <li class="nav-item mr-3"><i class="fas fa-store"></i><%= link_to "スポット", spots_path  %></li>
          <li class="nav-item mr-3"><i class="fas fa-sign-out-alt"></i><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>

        <% elsif admin_signed_in? %>

          <li class="nav-item mr-3"><i class="fas fa-store"></i><%= link_to "スポット", admin_spots_path %></li>
          <li class="nav-item mr-3"><i class="fas fa-user-friends"></i><%= link_to "会員一覧", admin_customers_path %></li>
          <li class="nav-item mr-3"><i class="fas fa-sign-out-alt"></i><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>

        <% else %>

          <li class="nav-item mr-3"><i class="fas fa-user-tag"></i><%= link_to 'ゲストログイン（閲覧用）', customers_guest_sign_in_path, method: :post %></li>
          <li class="nav-item mr-3"><i class="fas fa-pencil-alt"></i><%= link_to "新規登録", new_customer_registration_path %></li>
          <li class="nav-item mr-3"><i class="fas fa-sign-in-alt"></i><%= link_to "ログイン", new_customer_session_path %></li>
          
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nanisuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/e1ae299e11.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/flashmessage" %>
    </div>
      <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>